export const SCREEN_ROUTER = {
  MAIN: 'MAIN',
  AUTH: 'AUTH',
  SPLASH: 'SPLASH'
};
export const SCREEN_ROUTER_AUTH = {
  LOGIN: 'LOGIN',
  FORGOT_PASS: 'FORGOT_PASS',
  REGISTER: 'REGISTER'
};
export const SCREEN_ROUTER_APP = {
  HOME: 'HOME',
  USER: 'USER',
  HOME_DETAIL: 'HOME_DETAIL',
  USER_DETAIL: 'USER_DETAIL',
  TRANSPORT: 'TRANSPORT',
  SERVICE: 'SERVICE',
  COMMERCE: 'COMMERCE',
  IMAGE_VIEW: 'IMAGE_VIEW'
};
